[versions]
# @keep
minSdk = "21"
agp = "7.4.0"
kotlin = "1.8.0"
detekt = "1.22.0"
compose = "1.3.3"
compose-desktop = "1.3.0-rc05"

[libraries]
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-foundation = "androidx.compose.foundation:foundation:1.3.1"
compose-material3-android = "androidx.compose.material3:material3:1.0.1"
compose-material3-desktop = "rg.jetbrains.compose.material3:material3-desktop:1.2.1"

[bundles]
compose = [
    "compose-ui",
    "compose-ui-preview",
    "compose-ui-tooling",
    "compose-foundation",
    "compose-material3-android",
]

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
versions-check = "com.github.ben-manes.versions:0.44.0"
versions-update = "nl.littlerobots.version-catalog-update:0.7.0"
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-compose= { id = "org.jetbrains.compose", version.ref = "compose-desktop" }
