jwt:
  realm: default
  secret: "deadbeef"
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/hello/"

ktor:
  environment: dev
  deployment:
    port: 8080
  application:
    modules:
      - com.alapshin.multiplayground.ApplicationKt.module

database:
  filename: "database.sqlite"