jwt:
  secret: "deadbeef"

ktor:
  environment: dev
  deployment:
    port: 8080
  application:
    modules:
      - com.alapshin.multiplayground.ApplicationKt.module

database:
  filename: "database.sqlite"