style:
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview' ]
  WildcardImport:
    excludeImports: [ 'java.util.*', 'kotlinx.android.synthetic.*', 'io.ktor.*' ]

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][_A-Za-z0-9]*'
